name: deploy
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Move files to deploy into deploy folder
        run: |
          mkdir _deploy
          echo "${{ secrets.ENV_FILE }}" > _deploy/.env
          mv ./build _deploy
          mv ./package.json _deploy
          mv ./pnpm-lock.yaml _deploy

      - name: Copy build to server
        uses: easingthemes/ssh-deploy@main
        env:
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "_deploy/"
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.SERVER_HOST }}
          REMOTE_PORT: ${{ secrets.SERVER_PORT }}
          REMOTE_USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_TARGET }}

      - name: Redeploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd ${{ secrets.SERVER_TARGET }}
            pnpm install --prod --frozen-lockfile
            pm2 delete $(pwd | awk -F / '{print $NF}')
            pm2 start "pnpm start:prod" --name $(pwd | awk -F / '{print $NF}')
