name: lint

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Sort package json
        run: pnpm lint:sort-package-json

      - name: Run prettier
        uses: wearerequired/lint-action@v1
        with:
          auto_fix: true
          git_no_verify: true
          neutral_check_on_warning: true
          prettier: true
