name: lint
on:
  push:
  pull_request:
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linters
        run:
          - pnpm run lint

      - name: Commit files
        run: |
          git config --local user.email "arora.ryan@gmail.com"
          git config --local user.name "Github Actions"
          git commit -am "style: Lint code"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
